'use client';
import { useState, type FormEvent } from 'react';
import { Brand } from './brand';
import { Icon } from './icons';
import { webRequest } from './api';

export function Login({ onLogin }: { onLogin: (username: string) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const session = await webRequest<{ username: string }>('/api/admin/session', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username, password }) }); setPassword(''); onLogin(session.username); } catch (err) { setError(err instanceof Error ? err.message : 'Login gagal.'); } finally { setBusy(false); } }
  return <main className="flex min-h-dvh flex-col bg-[#0c0e11]"><header className="border-b border-white/[.07] px-6 py-5 sm:px-10"><Brand /></header><div className="grid flex-1 place-items-center px-5 py-12"><section className="w-full max-w-[410px]"><div className="mb-6 grid size-12 place-items-center rounded-xl border border-white/10 bg-white/[.03] text-[#a2a8b1]"><Icon name="lock" width={22} height={22} /></div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8d949e]">Private workspace</p><h1 className="mt-3 text-[30px] font-semibold tracking-tight">Masuk ke dashboard</h1><p className="mt-3 text-sm leading-6 text-[#8c939d]">Satu tempat untuk meninjau receipt, pembelian Robux, dan status pemberian item.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-xs font-medium text-[#c5cad1]" htmlFor="username">Username<input id="username" value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" maxLength={100} required className="field mt-2 w-full" placeholder="Username admin" /></label><label className="block text-xs font-medium text-[#c5cad1]" htmlFor="password">Password<input id="password" value={password} onChange={e => setPassword(e.target.value)} type="password" autoComplete="current-password" maxLength={256} required className="field mt-2 w-full" placeholder="Password admin" /></label>{error && <p role="alert" className="rounded-lg border border-red-400/20 bg-red-400/[.05] p-3 text-xs leading-5 text-red-300">{error}</p>}<button disabled={busy} className="flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#e8ebef] text-sm font-semibold text-[#15181d] transition-colors hover:bg-white disabled:opacity-50">{busy ? 'Memeriksa…' : 'Masuk dashboard'}<Icon name="arrow" width={16} height={16} /></button></form><p className="mt-6 flex items-center gap-2 text-[11px] text-[#686f7a]"><Icon name="lock" width={12} height={12} /> Akses khusus admin · Koneksi terenkripsi</p></section></div><footer className="px-6 py-5 text-center text-[11px] text-[#555e69]">RBXDB · Purchase audit workspace</footer></main>;
}
